import json
import os
import queue
import re
import threading
import time
import uuid
from datetime import datetime

import requests
from flask import Flask, Response, jsonify, render_template, request, send_from_directory
from fpdf import FPDF

app = Flask(__name__)
BOOKS_DIR = os.path.join(os.path.dirname(__file__), "books")
os.makedirs(BOOKS_DIR, exist_ok=True)

# Active generation sessions keyed by session_id
sessions: dict[str, dict] = {}
sessions_lock = threading.Lock()


# ---------------------------------------------------------------------------
# PDF helper
# ---------------------------------------------------------------------------

def _latin1_safe(text: str) -> str:
    """Replace characters not representable in latin-1 with ASCII equivalents."""
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2022": "*",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class BookPDF(FPDF):
    def __init__(self, title: str, author: str = "liteproducer"):
        super().__init__()
        self.book_title = _latin1_safe(title)
        self.book_author = author
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 8, self.book_title, align="C")
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def build_pdf(title: str, chapters: list[dict]) -> str:
    """Render chapters list to a PDF file and return its path."""
    pdf = BookPDF(title)
    pdf.set_title(title)

    # Cover page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 30, 30)
    pdf.ln(40)
    pdf.multi_cell(0, 12, _latin1_safe(title), align="C")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, f"Generated by liteproducer  -  {datetime.now().strftime('%B %d, %Y')}", align="C")

    for ch in chapters:
        pdf.add_page()
        # Chapter heading
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(30, 30, 30)
        pdf.ln(4)
        pdf.multi_cell(0, 10, _latin1_safe(ch.get("heading", "Chapter")), align="L")
        pdf.ln(4)
        pdf.set_draw_color(60, 100, 200)
        pdf.set_line_width(0.5)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(6)
        # Body
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 30, 30)
        body = ch.get("text", "")
        for para in body.split("\n"):
            para = para.strip()
            if para:
                pdf.multi_cell(0, 6, _latin1_safe(para), align="J")
                pdf.ln(3)

    safe_title = re.sub(r"[^\w\- ]", "", title)[:60].strip().replace(" ", "_")
    filename = f"{safe_title}_{uuid.uuid4().hex[:6]}.pdf"
    path = os.path.join(BOOKS_DIR, filename)
    pdf.output(path)
    return filename


# ---------------------------------------------------------------------------
# Generation logic
# ---------------------------------------------------------------------------

def call_api(
    endpoint: str,
    api_key: str,
    model: str,
    messages: list[dict],
    stream: bool = True,
    on_token=None,
    is_cancelled=None,
) -> str:
    """Call a chat completions endpoint, stream tokens, return full text."""
    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    payload = {
        "model": model,
        "messages": messages,
        "stream": stream,
    }

    full_text = ""
    try:
        with requests.post(
            endpoint,
            headers=headers,
            json=payload,
            stream=True,
            timeout=120,
        ) as resp:
            resp.raise_for_status()
            if stream:
                for raw_line in resp.iter_lines():
                    if is_cancelled and is_cancelled():
                        break
                    if not raw_line:
                        continue
                    line = raw_line.decode("utf-8", errors="replace")
                    if line.startswith("data:"):
                        data = line[5:].strip()
                        if data == "[DONE]":
                            break
                        try:
                            obj = json.loads(data)
                            delta = (
                                obj.get("choices", [{}])[0]
                                .get("delta", {})
                                .get("content", "")
                            )
                            if delta:
                                full_text += delta
                                if on_token:
                                    on_token(delta)
                        except json.JSONDecodeError:
                            pass
            else:
                obj = resp.json()
                full_text = (
                    obj.get("choices", [{}])[0]
                    .get("message", {})
                    .get("content", "")
                )
                if on_token and full_text:
                    on_token(full_text)
    except Exception as exc:
        error_msg = f"\n[API error: {exc}]\n"
        full_text += error_msg
        if on_token:
            on_token(error_msg)

    return full_text


def generate_book(session_id: str):
    """Background thread: generate chapters and push events to the session queue."""

    def sess():
        with sessions_lock:
            return sessions.get(session_id)

    def push(event: str, data):
        s = sess()
        if s:
            s["queue"].put({"event": event, "data": data})

    def is_cancelled():
        with sessions_lock:
            current = sessions.get(session_id, {})
            return bool(current.get("cancelled"))

    s = sess()
    if not s:
        return

    cfg = s["config"]
    endpoint = cfg["endpoint"]
    api_key = cfg.get("api_key", "")
    model = cfg.get("model", "gpt-3.5-turbo")
    genre = cfg.get("genre", "fiction")
    plot = cfg.get("plot", "")
    num_chapters = int(cfg.get("num_chapters", 5))
    title = cfg.get("title", "") or f"A {genre.title()} Story"

    push("status", {"msg": f'Starting book: "{title}"', "phase": "outline"})

    # ---- Build outline ----
    outline_prompt = (
        f'You are a creative author. Write a detailed chapter-by-chapter outline for a {genre} book '
        f'titled "{title}".\n'
    )
    if plot:
        outline_prompt += f"The plot is: {plot}\n"
    outline_prompt += (
        f"Produce exactly {num_chapters} chapters. For each chapter provide:\n"
        "CHAPTER N: <short title>\nSUMMARY: <2-3 sentence description>\n\n"
        "Only output the outline, nothing else."
    )

    push("log", f"Generating outline for {num_chapters} chapters…")
    outline_tokens: list[str] = []

    def on_outline_token(tok):
        outline_tokens.append(tok)
        push("token", {"phase": "outline", "text": tok})

    outline_text = call_api(
        endpoint,
        api_key,
        model,
        [{"role": "user", "content": outline_prompt}],
        stream=True,
        on_token=on_outline_token,
        is_cancelled=is_cancelled,
    )

    if is_cancelled():
        push("status", {"msg": "Generation cancelled.", "phase": "done"})
        push("done", {})
        return

    # Parse chapter headings from outline
    chapter_headings: list[str] = []
    for line in outline_text.splitlines():
        m = re.match(r"(?:CHAPTER\s+\d+|Chapter\s+\d+)[:\.\-–]\s*(.+)", line)
        if m:
            chapter_headings.append(m.group(1).strip())

    if not chapter_headings:
        # Fallback: just number them
        chapter_headings = [f"Chapter {i+1}" for i in range(num_chapters)]
    else:
        chapter_headings = chapter_headings[:num_chapters]
        while len(chapter_headings) < num_chapters:
            chapter_headings.append(f"Chapter {len(chapter_headings)+1}")

    push("outline_done", {"headings": chapter_headings})

    messages = [
        {
            "role": "system",
            "content": (
                f"You are a skilled {genre} author writing a book titled \"{title}\". "
                "Write vivid, immersive prose. Each chapter should be at least 800 words."
            ),
        },
        {
            "role": "user",
            "content": outline_text,
        },
    ]

    chapters: list[dict] = []

    for i, heading in enumerate(chapter_headings):
        # Check if cancelled
        if is_cancelled():
            push("status", {"msg": "Generation cancelled.", "phase": "done"})
            push("done", {})
            return

        # Collect any pending user instructions
        with sessions_lock:
            current = sessions.get(session_id, {})
            instructions = current.get("instructions", [])
            current["instructions"] = []

        chapter_num = i + 1
        full_heading = f"Chapter {chapter_num}: {heading}"
        push("status", {"msg": f"Writing {full_heading}…", "phase": "chapter", "chapter": chapter_num})
        push("chapter_start", {"num": chapter_num, "heading": full_heading})

        chapter_prompt = f"Write {full_heading} of the book in full."
        if instructions:
            chapter_prompt += "\n\nAdditional instructions from the author:\n" + "\n".join(
                f"- {inst}" for inst in instructions
            )

        messages.append({"role": "user", "content": chapter_prompt})

        chapter_tokens: list[str] = []

        def make_on_token(ch_num):
            def on_token(tok):
                chapter_tokens.append(tok)
                push("token", {"phase": "chapter", "chapter": ch_num, "text": tok})
            return on_token

        chapter_text = call_api(
            endpoint,
            api_key,
            model,
            messages,
            stream=True,
            on_token=make_on_token(chapter_num),
            is_cancelled=is_cancelled,
        )

        if is_cancelled():
            push("status", {"msg": "Generation cancelled.", "phase": "done"})
            push("done", {})
            return

        messages.append({"role": "assistant", "content": chapter_text})
        chapters.append({"heading": full_heading, "text": chapter_text})
        push("chapter_done", {"num": chapter_num, "heading": full_heading})

    # Build PDF
    push("status", {"msg": "Assembling PDF…", "phase": "pdf"})
    try:
        filename = build_pdf(title, chapters)
        push("pdf_ready", {"filename": filename, "title": title})
        push("status", {"msg": f"Book complete! Download: {filename}", "phase": "done"})
    except Exception as exc:
        push("status", {"msg": f"PDF error: {exc}", "phase": "error"})

    push("done", {})


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/start", methods=["POST"])
def start_generation():
    data = request.get_json(force=True)
    if not data.get("endpoint"):
        return jsonify({"error": "API endpoint is required"}), 400

    session_id = uuid.uuid4().hex
    with sessions_lock:
        sessions[session_id] = {
            "config": data,
            "queue": queue.Queue(),
            "instructions": [],
            "cancelled": False,
        }

    thread = threading.Thread(target=generate_book, args=(session_id,), daemon=True)
    thread.start()

    return jsonify({"session_id": session_id})


@app.route("/api/instruct/<session_id>", methods=["POST"])
def add_instruction(session_id: str):
    data = request.get_json(force=True)
    instruction = (data.get("instruction") or "").strip()
    if not instruction:
        return jsonify({"error": "No instruction provided"}), 400

    with sessions_lock:
        s = sessions.get(session_id)
        if not s:
            return jsonify({"error": "Session not found"}), 404
        s["instructions"].append(instruction)

    return jsonify({"ok": True})


@app.route("/api/cancel/<session_id>", methods=["POST"])
def cancel_generation(session_id: str):
    with sessions_lock:
        s = sessions.get(session_id)
        if not s:
            return jsonify({"error": "Session not found"}), 404
        s["cancelled"] = True
    return jsonify({"ok": True})


@app.route("/api/events/<session_id>")
def event_stream(session_id: str):
    def generate():
        timeout = 600  # 10 minutes max
        deadline = time.time() + timeout
        while time.time() < deadline:
            with sessions_lock:
                s = sessions.get(session_id)
            if not s:
                yield "data: {}\n\n"
                break
            try:
                item = s["queue"].get(timeout=1)
                payload = json.dumps({"event": item["event"], "data": item["data"]})
                yield f"data: {payload}\n\n"
                if item["event"] == "done":
                    break
            except queue.Empty:
                yield ": keep-alive\n\n"

    return Response(
        generate(),
        mimetype="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@app.route("/api/books")
def list_books():
    files = sorted(
        [f for f in os.listdir(BOOKS_DIR) if f.endswith(".pdf")],
        key=lambda f: os.path.getmtime(os.path.join(BOOKS_DIR, f)),
        reverse=True,
    )
    return jsonify({"books": files})


@app.route("/books/<path:filename>")
def download_book(filename: str):
    return send_from_directory(BOOKS_DIR, filename, as_attachment=True)


if __name__ == "__main__":
    debug = os.environ.get("FLASK_DEBUG", "0") == "1"
    app.run(debug=debug, host="0.0.0.0", port=5000, threaded=True)
