/**
 * PDF generation module for liteproducer PWA.
 * Uses jsPDF for client-side PDF creation.
 */
import { jsPDF } from 'jspdf';

/**
 * Build a PDF from a book title and chapters.
 * @param {string} title - Book title.
 * @param {Array<{heading: string, text: string}>} chapters - Chapter data.
 * @returns {Blob} - PDF file as a Blob.
 */
export function buildPDF(title, chapters) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const textWidth = pageWidth - margin * 2;

  // Cover page
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(title, pageWidth / 2, 80, { align: 'center', maxWidth: textWidth });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(`Generated by liteproducer — ${date}`, pageWidth / 2, 100, { align: 'center' });

  // Chapters
  for (const chapter of chapters) {
    doc.addPage();
    doc.setTextColor(30, 30, 30);

    // Chapter heading
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(chapter.heading || 'Chapter', margin, 30, { maxWidth: textWidth });

    // Separator line
    doc.setDrawColor(60, 100, 200);
    doc.setLineWidth(0.5);
    doc.line(margin, 35, pageWidth - margin, 35);

    // Body text
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(chapter.text || '', textWidth);
    let y = 42;
    const lineHeight = 5;
    const pageHeight = doc.internal.pageSize.getHeight();

    for (const line of lines) {
      if (y + lineHeight > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    }
  }

  return doc.output('blob');
}

/**
 * Trigger a download of the PDF blob.
 * @param {Blob} blob - PDF blob.
 * @param {string} filename - Desired filename.
 */
export function downloadPDF(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
